name: Docker build and deploy

env:
  DOTNET_VERSION: '6.x'
on:
  push:
    branches:
      - yaml

jobs:
  build:
    runs-on: self-hosted
    environment: develop
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: d58526/TicketSystem:latest
        
    
      
    
    
      
          
          
    
